import asyncio

from src.agent_state import AgentState
from src.config import settings
from src.schemas import DeveloperResult, PendingAction
from src.skills.developer import DevToolsClient

dev_client = DevToolsClient()


def classify_operation(query: str) -> str:
    """Map a developer request to a concrete operation."""
    q = query.lower()
    if "clipboard" in q:
        return "clipboard"
    if "scaffold" in q or "create" in q or "file" in q:
        return "scaffold"
    return "none"


def is_side_effecting(operation: str) -> bool:
    """Clipboard read is safe; file writes / launches mutate the system."""
    return operation in ("scaffold",)


async def execute_developer_action(operation: str, query: str) -> DeveloperResult:
    """
    Perform the operation. Shared by the graph node (read-only / approved) and
    the /confirm endpoint (approved side-effecting actions). (L4)
    """
    if operation == "clipboard":
        text = await asyncio.to_thread(dev_client.read_clipboard)
        return DeveloperResult(operation="clipboard", ok=True, content=text)

    if operation == "scaffold":
        if not settings.approved_workspace_paths:
            return DeveloperResult(operation="scaffold", ok=False,
                                   error="No approved workspace directories configured.")
        folder = settings.approved_workspace_paths[0]
        content = (
            f"# Scaffold Project\nGenerated by Lyra Desktop Assistant\n"
            f"Command context: {query}"
        )
        path = await asyncio.to_thread(dev_client.write_scaffold, "README.md", content, folder)
        result = DeveloperResult(operation="scaffold", ok=True, path=path)
        if "code" in query.lower() or "vscode" in query.lower():
            await asyncio.to_thread(dev_client.launch_vs_code, folder)
            result.launched_vscode = True
        return result

    return DeveloperResult(operation="none", ok=False, error="No matching developer command.")


async def developer_skill_node(state: AgentState) -> dict:
    query = state["query"]
    operation = classify_operation(query)
    logs = [f"Developer mode: operation='{operation}'."]

    # ── Human-in-the-loop gate for side-effecting operations (L4) ─────────────
    already_approved = bool((state.get("pending_action") or {}).get("approved"))
    if is_side_effecting(operation) and not already_approved:
        pending = PendingAction(
            skill="developer",
            operation=operation,
            description=f"Create a scaffold file in the approved workspace for: “{query}”.",
            payload={"query": query},
        )
        logs.append("Side-effecting action requires confirmation — awaiting approval.")
        return {
            "action_logs": logs,
            "skill_result": DeveloperResult(operation=operation, ok=False,
                                            error="awaiting_confirmation").model_dump(),
            "pending_action": pending.model_dump(),
            "final_response": (
                f"This will create a file in your approved workspace. "
                f"Shall I proceed? You can approve or deny below."
            ),
            "direct_response": True,
        }

    try:
        result = await execute_developer_action(operation, query)
        logs.append(f"Developer result: ok={result.ok} op={result.operation}")
    except Exception as e:
        logs.append(f"Developer skill execution failed: {e}")
        result = DeveloperResult(operation=operation, ok=False, error=str(e))

    return {"action_logs": logs, "skill_result": result.model_dump()}
