from src.agent_state import AgentState
from src.skills.developer import DevToolsClient
from src.config import settings

dev_client = DevToolsClient()

def developer_skill_node(state: AgentState) -> dict:
    query = state["query"].lower()
    logs = ["Entering Developer Command Mode."]
    
    try:
        if "clipboard" in query:
            clipboard_text = dev_client.read_clipboard()
            logs.append(f"Successfully read clipboard text: '{clipboard_text[:150]}...'")
            logs.append(f"Full Clipboard Content:\n{clipboard_text}")
            
        elif "scaffold" in query or "create" in query or "file" in query:
            if not settings.approved_workspace_paths:
                raise ValueError("No approved workspace directories specified in settings.")
                
            folder = settings.approved_workspace_paths[0]
            
            # Simple markdown README scaffold
            filename = "README.md"
            content = f"# Scaffold Project\nGenerated by Lyra Desktop Assistant\nCommand context: {state['query']}"
            
            written_path = dev_client.write_scaffold(filename, content, folder)
            logs.append(f"Successfully generated scaffold file at: {written_path}")
            
            if "code" in query or "vscode" in query:
                dev_client.launch_vs_code(folder)
                logs.append("Triggered VS Code launch process.")
        else:
            logs.append("No matches found for specific developer commands.")
            
    except Exception as e:
        logs.append(f"Developer skill execution failed: {str(e)}")
        
    return {
        "action_logs": logs
    }
