import asyncio

from src.agent_state import AgentState
from src.skills.developer import DevToolsClient
from src.config import settings

dev_client = DevToolsClient()


async def developer_skill_node(state: AgentState) -> dict:
    query = state["query"].lower()
    logs = ["Entering Developer Command Mode."]
    result = {"operation": "none", "ok": False}

    try:
        if "clipboard" in query:
            clipboard_text = await asyncio.to_thread(dev_client.read_clipboard)
            logs.append(f"Successfully read clipboard text: '{clipboard_text[:150]}...'")
            result = {"operation": "clipboard", "ok": True, "content": clipboard_text}

        elif "scaffold" in query or "create" in query or "file" in query:
            if not settings.approved_workspace_paths:
                raise ValueError("No approved workspace directories specified in settings.")

            folder = settings.approved_workspace_paths[0]
            filename = "README.md"
            content = (
                f"# Scaffold Project\nGenerated by Lyra Desktop Assistant\n"
                f"Command context: {state['query']}"
            )
            written_path = await asyncio.to_thread(dev_client.write_scaffold, filename, content, folder)
            logs.append(f"Successfully generated scaffold file at: {written_path}")
            result = {"operation": "scaffold", "ok": True, "path": written_path}

            if "code" in query or "vscode" in query:
                await asyncio.to_thread(dev_client.launch_vs_code, folder)
                logs.append("Triggered VS Code launch process.")
                result["launched_vscode"] = True
        else:
            logs.append("No matches found for specific developer commands.")

    except Exception as e:
        logs.append(f"Developer skill execution failed: {str(e)}")
        result = {"operation": result.get("operation", "none"), "ok": False, "error": str(e)}

    return {"action_logs": logs, "skill_result": result}
